### Q1

In [3]:
import numpy as np
import matplotlib.pyplot as plt
# from scipy import linalg
import numpy.linalg as nl

a1_1 = np.array([[1,2],[3,4]])
a1_2 = np.array([[1,2],[3,4],[5,6]])


In [4]:
nl.eig(a1_1)
# eigenvalue 2개와 eigen vector 2개가 나온다.


(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [8]:
# linalg.eig(a1_2) # error
# 정사각행렬이 아니라서 에러 나옴

In [9]:
nl.svd(a1_1, full_matrices=True)
# 2x2 left singular matrix, 1x2의 singular value matrix, 2x2 right singularmatrix 반환. full matrix 형태

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [38]:
nl.svd(a1_1, full_matrices=False)
# 2x2 left singular matrix, 1x2의 singular value matrix, 2x2 right singularmatrix 반환. 정사각행렬이라 full matrix 형태

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [39]:
nl.svd(a1_2, full_matrices=True)
# 3x3 left singular matrix, 1x2의 singular value matrix, 2x2 right singularmatrix 반환. full matrix 형태

(array([[-0.2298477 ,  0.88346102,  0.40824829],
        [-0.52474482,  0.24078249, -0.81649658],
        [-0.81964194, -0.40189603,  0.40824829]]),
 array([9.52551809, 0.51430058]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))

In [11]:
nl.svd(a1_2, full_matrices=False)
# 3x2 left singular matrix, 1x2의 singular value matrix, 2x2 right singularmatrix 반환. full matrix 형태로 나오지 않음

(array([[-0.2298477 ,  0.88346102],
        [-0.52474482,  0.24078249],
        [-0.81964194, -0.40189603]]),
 array([9.52551809, 0.51430058]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))

### 2

In [13]:
a2 = np.array([[7,1],[1,7]])
x,y = nl.eig(a2)
x,y
# x는 eigenvalue, y는 eigenvector
# egienvalue: Av = av 만족하는 a
# eigenvector: Av = av 만족하는 v

(array([8., 6.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

### 3

In [27]:
a3 = np.array([[1,1,1,0,0], [3,3,3,0,0], [4,4,4,0,0],
              [5,5,5,0,0], [0,2,0,4,4], [0,0,0,5,5], [0,1,0,2,2]])
U,S,V = nl.svd(a3, full_matrices=False)
U,S,V
U.shape
# U: 7x5 형태의 left singular매트릭스 a3를 singular value decomposition 결과 return
# full_matrices=False라서 7x7 형태가 아닌 7x5 형태로 출력
# S: 1x5, 원래 diagonal 형태이나 1차원 vector로 출력
# V: 5x5 형태의 right singular



(7, 5)

### 4

In [33]:
a4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
a4.reshape(3,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [34]:
for i in a4.reshape(3,2,3):
    for j in i:
        print(j)
        print('-------')

[1 2 3]
-------
[4 5 6]
-------
[7 8 9]
-------
[10 11 12]
-------
[13 14 15]
-------
[16 17 18]
-------


### 5

In [37]:
a5 = np.array([[1,2],[3,4]])
b5 = np.array([[1,3],[2,4]])

In [38]:
np.dot(a5, b5) # matrix 곱

array([[ 5, 11],
       [11, 25]])

In [39]:
a5*b5 # element-wise 곱

array([[ 1,  6],
       [ 6, 16]])

### 6

In [64]:
a6_1 = np.zeros((5,5))
a6_1 += np.arange(5) # broadcasting
a6_1

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [41]:
a6_2 = np.full((4,5,3), 3)
# np.cov(a6_2)
# a6_2 # 2차원이 아닌 3차원 데이터를 받았기 때문에 error 발생
