<a href="https://colab.research.google.com/github/sangqkim/DS2/blob/master/191023_TF_basic_sol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. TensorFlow Ops

## Graph and Session
**Graph** : It contains a set of Operations (units of computation) and Tensors (data flow between operations).

**Session** : It encapsulates an execution environment such as which operations are executed and what is the current values of Tensor objects. 

Let's learn Graph and Session using examples presented below.

## Constant Op

Let's create a constant in TensorFlow.

**```tf.constant(value, dtype = None, shape = None, name = 'Const', verify_shape = False)```**

In [1]:
import tensorflow as tf

graph = tf.Graph()
with graph.as_default():
  # constant of 1d tensor, or a vector
  a = tf.constant([2,2], name = 'vector')

  # constant of 2x2 tensor, or a matrix
  b = tf.constant([[0,2], [1,3]], name = 'matrix')

print(a)
print(b)

Tensor("vector:0", shape=(2,), dtype=int32)
Tensor("matrix:0", shape=(2, 2), dtype=int32)


In [0]:
# Get values of a and b
with tf.Session(graph=graph) as sess:
  print('a: ')
  print(sess.run(a))
  print('\nb:')
  print(sess.run(b))

a: 
[2 2]

b:
[[0 2]
 [1 3]]


## Math Ops
The following example shows a matrix division op.

In [0]:
graph = tf.Graph()
with graph.as_default():
  # Create constant a and b
  a = tf.constant([2,4], name = 'a', dtype = tf.float32)
  b = tf.constant([[0,1], [2,3]], name = 'b', dtype = tf.float32)
  
  # Create divide operation using b and a
  div = tf.div(b, a)
  # or equivalently, div = b / a
  # div = b / a

print('Print information of div op')
print(div.op)

print('\nPrint div tensor')
print(div)

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Print information of div op
name: "div"
op: "RealDiv"
input: "b"
input: "a"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}


Print div tensor
Tensor("div:0", shape=(2, 2), dtype=float32)


Run div operations.

In [0]:
with tf.Session(graph=graph) as sess:
  print('\nPrint div')
  print(sess.run(div))


Print div
[[0.   0.25]
 [1.   0.75]]


## Quiz 1
**Define a graph with two constants with shape=[2, 2] and a matmul operation. Print the values of c.
(X: matrix multiplication, HINT: use tf.matmul) **

In [0]:
import tensorflow as tf

graph = tf.Graph()
with graph.as_default():
  ############# Write here. ################
  a = tf.constant([[1, 2], [3, 4]])
  b = tf.constant([[1, -1], [1, 1]])
  c = tf.matmul(a, b)
  ##########################################

with tf.Session(graph=graph) as sess:
  print(sess.run(c))

[[3 1]
 [7 1]]


## Variables

TensorFlow object to store mutable state (e.g., model parameters) across multiple session runs.

### Creating variables

To declare a variable, you create an instance of the class tf.Variable. tf.constant is written as lowercase because it's an op, and tf.Variable is written with a capital "V" because it encapsulates multiple ops.

#### Usage of TF Variables


```
x = tf.Variable(...)
x               # variable op
x.initializer   # initialization ops
x.value         # read op
x.assign(...)   # write op
x.assign_add(...) # x += ...
```



One way to create a variable is: 

**```tf.Variable(< initial-value >, name = < optional-name >)```**

This example creates three variables using `tf.Variable`.

In [0]:
graph = tf.Graph()
with graph.as_default():
  # Create scalar variable
  s = tf.Variable(2, name = 'scalar')
  # Create matrix variable
  m = tf.Variable([[0,1], [2,3]], name = 'matrix')
  # Create zero matrix using tf.zeros
  W = tf.Variable(tf.zeros([784,10]))

In [0]:
# with tf.Session(graph=graph) as sess:
#   print('s:')
#   print(sess.run(s))
#   print('\nm:')
#   print(sess.run(m))
#   print('\nW:')
#   print(sess.run(W))

### Initialize variables

Before using a variable, you must initialize it, or else you'll run into an error.

In [0]:
with tf.Session(graph=graph) as sess:
  # Run initialization op
  sess.run(s.initializer)
  sess.run(m.initializer)
  sess.run(W.initializer)

  print('s:')
  print(sess.run(s))
  print('\nm:')
  print(sess.run(m))
  print('\nW:')
  print(sess.run(W))

s:
2

m:
[[0 1]
 [2 3]]

W:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


To initiliaze all variables at once: use **`tf.global_variables_initializer()`**

In [0]:
with tf.Session(graph=graph) as sess:
  # Run initialization ops of all variables
  sess.run(tf.global_variables_initializer())

  print('s:')
  print(sess.run(s))
  print('\nm:')
  print(sess.run(m))
  print('\nW:')
  print(sess.run(W))

s:
2

m:
[[0 1]
 [2 3]]

W:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


More encouraged way is using **`tf.get_variable`**, which allows us to provide the variable's internal name, shape, type, and initializer to give the variable its initial value.

```
tf.get_variable(
    name,
    shape=None,
    dtype=None,
    initializer=None,
    regularizer=None,
    trainable=True,
    collections=None,
    caching_device=None,
    partitioner=None,
    validate_shape=True,
    use_resource=None,
    custom_getter=None,
    constraint=None
)
```

Create three variables using `tf.get_variable`

In [0]:
graph = tf.Graph()
with graph.as_default():
  s = tf.get_variable('scalar', initializer=tf.constant(3))
  m = tf.get_variable('matrix', initializer=tf.constant([[0,2], [1,3]]))
  W = tf.get_variable('big_matrix', shape=(784, 10), initializer=tf.ones_initializer())

In [0]:
with tf.Session(graph=graph) as sess:
  # Run initialization ops of all variables
  sess.run(tf.global_variables_initializer())

  print('s:')
  print(sess.run(s))
  print('\nm:')
  print(sess.run(m))
  print('\nW:')
  print(sess.run(W))

s:
3

m:
[[0 2]
 [1 3]]

W:
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


### Changing values of variables

To change the value of a variable, we need to assign a new value to the variable.
You can see variable `v` changes after `assign` operations are executed.

In [0]:
graph = tf.Graph()
with graph.as_default():
  # v is a 2 x 3 variable of random values
  v = tf.get_variable('normal_matrix', shape=(2,3), initializer=tf.random_normal_initializer(mean=0., stddev=1.))
  c = tf.constant(1.0, shape=(2,3))
  assign_1 = v.assign(c)
  assign_2 = v.assign([[1., 2., 3.], [4., 5., 6.]])

with tf.Session(graph=graph) as sess:
  # Initialize variables
  sess.run(tf.global_variables_initializer())
  # or equivalently
  # sess.run(v.initializer)
  
  # Get value
  print('v:')
  print(sess.run(v))

  # Assign new value to the variable
  sess.run(assign_1)

  # Get value again
  print('v:')
  print(sess.run(v))

  # Initialize the variable once again to random values
  sess.run(v.initializer)

  # Get value again
  print('v:')
  print(sess.run(v))

  # Assign new value to the variable
  sess.run(assign_2)

  # Get value again
  print('v:')
  print(sess.run(v))

v:
[[-1.6561947   0.34310102  0.708068  ]
 [-0.4922949   0.8811715  -0.31449178]]
v:
[[1. 1. 1.]
 [1. 1. 1.]]
v:
[[-1.4980592  -2.6887426  -0.60777825]
 [ 0.56541526  0.79404986 -0.48953685]]
v:
[[1. 2. 3.]
 [4. 5. 6.]]


## Quiz 2
Define a variable (name : "term") with shape = [] and dtype = `tf.float64`. Initialize the variable as `2` first.
Define another variable (name : "sum") with shape = [] and dtype = `tf.float64`. Initialize the variable as zeros.

By using these two variables, compute the following:
sum = 1/term_1 + 1/term_2 + ... + 1/term_10
where
term_i = term_{i-1} * (term_{i-1} - 1) + 1
and term_1 = 2.
(This recurrence relation is known as Sylvester's sequence.)

Hint: Repeat updating the variables "sum" and "term" 10 times.


In [0]:
import tensorflow as tf

graph = tf.Graph()
with graph.as_default():
  ############# Write here. ################
  t = tf.get_variable('term', dtype=tf.float64, initializer=tf.constant(2., dtype=tf.float64))
  s = tf.get_variable('sum', dtype=tf.float64, initializer=tf.constant(0., dtype=tf.float64))
  update_t = t.assign(t * (t - 1) + 1)
  update_s = s.assign_add(1 / t)
  ##########################################

with tf.Session(graph=graph) as sess:
  ############# Write here. ################
  sess.run(tf.global_variables_initializer())
  for _ in range(10):
    sess.run(update_s)
    sess.run(update_t)
  ##########################################

  print('s:', sess.run(s))

s: 0.9999999999999999


# 2. Feeding Input Data into a TensorFlow Graph

How to feed data into a TensorFlow program?

Use `tf.Placeholder` or

**TensorFlow Dataset API (recommended for large-scale data)**

## Placeholder

TensorFlow's feed mechanism lets you inject data into any Tensor in a computation graph. Feed your data (usually a Numpy array) by passing the `feed_dict` argument to the `sess.run()` call.

TensorFlow provides a **placeholder** operation that must be fed with data on execution. A placeholder exists solely to serve as the target of feeds. It is not initialized and contains no data. A placeholder generates an error if it is executed without a feed, so you won't forget to feed it.

In [0]:
graph = tf.Graph()
with graph.as_default():
  # Create a constant with 1.
  a = tf.constant(1)

  # Create scalar placeholder with integer data type.
  b = tf.placeholder(shape=[], dtype=tf.int32)

  # Create add operation using the constant and placeholder.
  c = tf.add(a, b)
  
  with tf.Session(graph=graph) as sess:
    print('a:', sess.run(a))

    # cannot run the graph since we didn't feed value to the placeholder
    try:
      print('b:', sess.run(b))
    except Exception as e:
      print(e.message)

    # cannot run the graph since we didn't feed value to the placeholder
    try:
      print('c:', sess.run(c))
    except Exception as e:
      print(e.message)

    # feed value 2 to b (c = a + b = 1 + 2 = 3)
    print('c = 1 + 2 =', sess.run(c, feed_dict={b: 2}))

    # we can also feed a
    print('c = -1 + 2 =', sess.run(c, feed_dict={a: -1, b: 2}))

    # we can also feed c: in this case, we don't have to feed b since we don't need it
    print('c =', sess.run(c, feed_dict={c:0}))
    

a: 1
You must feed a value for placeholder tensor 'Placeholder' with dtype int32
	 [[node Placeholder (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
You must feed a value for placeholder tensor 'Placeholder' with dtype int32
	 [[node Placeholder (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
c = 1 + 2 = 3
c = -1 + 2 = 1
c = 0


## Quiz 3
Define a variable (name: `sum`, shape: [2, 3]).
Initialize the variable as zeros first.

Drawing random samples from a uniform distribution using `np.random.uniform(size=(2,3))`.

Accumulate the value of the sample to the variable 1200 times.
Subtract `600.0` from the variable and divide the variable by `10.0` to approximate a draw from standard normal distribution.

In [0]:
import numpy as np
import tensorflow as tf

graph = tf.Graph()
with graph.as_default():
  ############# Write here. ################
  sample = tf.placeholder(shape=(2,3), dtype=tf.float32)
  s = tf.get_variable('sum', shape=(2,3), initializer=tf.zeros_initializer())
  update_s = s.assign_add(sample)
  normalized = (s - 600.) / 10.
  ##########################################

with tf.Session(graph=graph) as sess:
  sess.run(tf.global_variables_initializer())

  ############# Write here. ################
  for _ in range(1200):
    sess.run(update_s, feed_dict={sample: np.random.uniform(size=(2,3))})
  print('approximate standard normal:')
  print(sess.run(normalized))
  ##########################################

approximate standard normal:
[[ 0.25338134  0.06036988 -0.34400636]
 [ 0.8322388  -0.59349364 -0.11800537]]


## Dataset

The `tf.data` API is the most advanced API for writing TensorFlow input pipelines.

It allows you to build complex pipelines by composing simple building blocks. 

Two main abstractions introduced by the `tf.data` API are:
* `tf.data.Dataset`: contains a sequence of items (each item represents one or more `tf.Tensor`s)
* `tf.data.Iterator`: provides interface to iterate through the dataset

Users can create new Datasets from existing `tf.Tensor`s by using static methods like `Dataset.from_tensor_slices()`. 

For example, you can create a Dataset of string Tensors that represents input file names. 

Transformation of exisiting Datasets is another way of creating new dataset. 

TensorFlow provides frequently-used Dataset transformations such as `Dataset.batch` or `Dataset.shuffle` (please refer to https://www.tensorflow.org/api_docs/python/tf/data/Dataset). 

An Iterator is associated with a particular Dataset and we can retrieve the next element by executing an operation returned by `Iterator.get_next()`. 

This typically acts as an interface between your Dataset input pipline and your model.

The simplest way to construct an Iterator is using `tf.compat.v1.data.make_one_shot_iterator(Dataset)`.



### `tf.data.Dataset.from_tensor_slices()`



Creates a Dataset whose elements are slices of the given *python array* or *numpy array* or *tensors*.

In [0]:
import numpy as np
arr = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

graph = tf.Graph()
with graph.as_default():
  # Create a dataset from a numpy array
  ds = tf.data.Dataset.from_tensor_slices(arr)
  
  # Create an iterator for the dataset
  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  
  # Retrieve next element from theiterator
  data_getter = iterator.get_next()
  
  # Multiply by 2
  mul_2 = data_getter * 2
  
  with tf.Session(graph=graph) as sess:
    for i in range(10):
      print(sess.run(mul_2))

0
2
4
6
8
10
12
14
16
18


## Create a dataset from files using the Dataset API

In [0]:
def iterate_and_print(iterator, graph, count=6):
  with tf.Session(graph=graph) as sess:
    # Read the first `count` elements of the iterator.
    for i in range(count):
      v = sess.run(iterator)
      print('step %d, data: %s' % (i, v))

### Create dummy binary files

In [0]:
import os
import numpy as np

def create_bin_file(file_name, value):
  with open(file_name, 'wb') as f:
    f.write(np.arange(value, value+4, dtype=np.int32))
    
bin_filenames = []
for i in range(3):
  file_name = 'binary_file_%d'% i
  create_bin_file(file_name, i)
  bin_filenames.append(file_name)

# first file:
# 0 1 2 3

# second file:
# 1 2 3 4

# third file:
# 2 3 4 5

### FixedLengthRecordDataset : each fixed-length slice of bytes is a dataset element.

In this example, each data instance is a 8-byte integer.

In [0]:
graph = tf.Graph()
with graph.as_default():
  # create a Dataset that contains slices (size: 8 bytes) of the files
  ds = tf.data.FixedLengthRecordDataset(bin_filenames, 8)
  # or equivalently,
  # ds = tf.data.Dataset.from_tensor_slices(bin_filenames)
  # ds = ds.apply(lambda filename: tf.data.FixedLengthRecordDataset(filename, 8))

  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  # contains raw byte strings
  iterator = iterator.get_next()
  # convert 8 bytes into int32 => two int32 value per each element
  to_int = tf.io.decode_raw(iterator, 'int32')

iterate_and_print(to_int, graph)

step 0, data: [0 1]
step 1, data: [2 3]
step 2, data: [1 2]
step 3, data: [3 4]
step 4, data: [2 3]
step 5, data: [4 5]


### Create dummy text files

In [0]:
def create_text_file(file_name, index):
  with open(file_name, 'w') as f:
    f.write('Hello_%d\n' % index)
    f.write('TensorFlow_%d\n' % index)

text_filenames = []
for i in range(3):
  file_name = 'text_file_%d'% i
  create_text_file(file_name, i)
  text_filenames.append(file_name)

# first file:
# Hello_0
# TensorFlow_0

# second file:
# Hello_1
# TensorFlow_1

# third file:
# Hello_2
# TensorFlow_2

### TextLineDataset : each text line is a dataset element.


In [0]:
graph = tf.Graph()
with graph.as_default():
  # create a Dataset that contains each line of the text files
  ds = tf.data.TextLineDataset(text_filenames)
  # or equivalently,
  # ds = tf.data.Dataset.from_tensor_slices(text_filenames)
  # ds = ds.apply(lambda filename: tf.data.TextLineDataset(filename))

  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  iterator = iterator.get_next()

iterate_and_print(iterator, graph)

step 0, data: b'Hello_0'
step 1, data: b'TensorFlow_0'
step 2, data: b'Hello_1'
step 3, data: b'TensorFlow_1'
step 4, data: b'Hello_2'
step 5, data: b'TensorFlow_2'


## Transform dataset

**ds.shffule(buffer_size)**

shuffle: shuffle data instances randomly. buffer size represents the number of data instances to be sampled.


`ds.shuffle` with N > 1 can pick data instances randomly from the buffer containing N instances. The code snippet below shows that we always do not get the 5th or 6th element of the dataset (Hello_2 or TensorFlow_2) at step 0.

In [0]:
graph = tf.Graph()
with graph.as_default():
  ds = tf.data.TextLineDataset(text_filenames) 
  # shuffle the dataset using buffer size 4
  ds = ds.shuffle(4)

  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  iterator = iterator.get_next()

iterate_and_print(iterator, graph)

step 0, data: b'Hello_1'
step 1, data: b'Hello_0'
step 2, data: b'Hello_2'
step 3, data: b'TensorFlow_1'
step 4, data: b'TensorFlow_0'
step 5, data: b'TensorFlow_2'


`ds.shuffle` with N == 1 has no shuffling effect.

In [0]:
graph = tf.Graph()
with graph.as_default():
  ds = tf.data.TextLineDataset(text_filenames)
  # shuffle the dataset using buffer size 1
  ds = ds.shuffle(1)

  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  iterator = iterator.get_next()

iterate_and_print(iterator, graph)

step 0, data: b'Hello_0'
step 1, data: b'TensorFlow_0'
step 2, data: b'Hello_1'
step 3, data: b'TensorFlow_1'
step 4, data: b'Hello_2'
step 5, data: b'TensorFlow_2'


**ds.repeat(count)**

Repeat the data instances count times. 

Without `ds.repeat()`, an error is raised after reading all the data from the dataset.

In [0]:
# graph = tf.Graph()
# with graph.as_default():
#   ds = tf.data.TextLineDataset(text_filenames)

#   iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
#   iterator = iterator.get_next()

# iterate_and_print(iterator, graph, count=7)

`ds.repeat(count)` repeats iterating the dataset `count` times. If we do not pass `count` argument, we can iterate forever.

In [0]:
graph = tf.Graph()
with graph.as_default():
  ds = tf.data.TextLineDataset(text_filenames)
  # repeat twice
  ds = ds.repeat(2)

  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  iterator = iterator.get_next()

iterate_and_print(iterator, graph, count=12)

step 0, data: b'Hello_0'
step 1, data: b'TensorFlow_0'
step 2, data: b'Hello_1'
step 3, data: b'TensorFlow_1'
step 4, data: b'Hello_2'
step 5, data: b'TensorFlow_2'
step 6, data: b'Hello_0'
step 7, data: b'TensorFlow_0'
step 8, data: b'Hello_1'
step 9, data: b'TensorFlow_1'
step 10, data: b'Hello_2'
step 11, data: b'TensorFlow_2'


Another common pattern is to use try-except clause to detect the end of epoch. Once we finisn an epoch, we re-initialize the iterator to start from the beginning again.

In [0]:
graph = tf.Graph()
with graph.as_default():
  ds = tf.data.TextLineDataset(text_filenames)

  # create an empty iterator with only type and shape information
  iterator = tf.data.Iterator.from_structure(tf.compat.v1.data.get_output_types(ds), tf.compat.v1.data.get_output_shapes(ds))

  # create an operation for initializing the iterator with the dataset
  init_iterator = iterator.make_initializer(ds)

  iterator = iterator.get_next()

epoch = 0
step = 0
with tf.Session(graph=graph) as sess:
  # initialize the iterator
  sess.run(init_iterator)
  
  while True:
    # repeat until we detect an error
    try:
      v = sess.run(iterator)
      print('step %d, data: %s' % (step, v))
      step += 1
    # iterator raises tf.errors.OutOfRangeError once we finish an epoch
    except tf.errors.OutOfRangeError:
      print('Finished epoch', epoch)
      epoch += 1
      # if we are done with 2 epochs, break
      if epoch >= 2:
        break
      # otherwise, re-initialize the iterator
      sess.run(init_iterator)

Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
step 0, data: b'Hello_0'
step 1, data: b'TensorFlow_0'
step 2, data: b'Hello_1'
step 3, data: b'TensorFlow_1'
step 4, data: b'Hello_2'
step 5, data: b'TensorFlow_2'
Finished epoch 0
step 6, data: b'Hello_0'
step 7, data: b'TensorFlow_0'
step 8, data: b'Hello_1'
step 9, data: b'TensorFlow_1'
step 10, data: b'Hello_2'
step 11, data: b'TensorFlow_2'
Finished epoch 1


**ds.batch(batch_size)**

Combines elements of this dataset into batches. `batch_size` represents the number of data instances to combine.

In [0]:
graph = tf.Graph()
with graph.as_default():
  ds = tf.data.TextLineDataset(text_filenames) 
  # batch elements using batch_size 3
  ds = ds.batch(3)
  ds = ds.repeat(3)

  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  iterator = iterator.get_next()

iterate_and_print(iterator, graph)

step 0, data: [b'Hello_0' b'TensorFlow_0' b'Hello_1']
step 1, data: [b'TensorFlow_1' b'Hello_2' b'TensorFlow_2']
step 2, data: [b'Hello_0' b'TensorFlow_0' b'Hello_1']
step 3, data: [b'TensorFlow_1' b'Hello_2' b'TensorFlow_2']
step 4, data: [b'Hello_0' b'TensorFlow_0' b'Hello_1']
step 5, data: [b'TensorFlow_1' b'Hello_2' b'TensorFlow_2']


**ds.map(fn)**

Apply `fn` to each element of the dataset.

In [0]:
# split the `data` tensor into 3 pieces and concatenate the pieces by inserting '+' between them
def split_join(data):
  data = tf.split(data, 3)
  return tf.strings.join(data, '+')

graph = tf.Graph()
with graph.as_default():
  ds = tf.data.TextLineDataset(text_filenames)
  ds = ds.batch(3)
  ds = ds.repeat(3)
  ds = ds.map(split_join)

  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  iterator = iterator.get_next()

iterate_and_print(iterator, graph)

step 0, data: [b'Hello_0+TensorFlow_0+Hello_1']
step 1, data: [b'TensorFlow_1+Hello_2+TensorFlow_2']
step 2, data: [b'Hello_0+TensorFlow_0+Hello_1']
step 3, data: [b'TensorFlow_1+Hello_2+TensorFlow_2']
step 4, data: [b'Hello_0+TensorFlow_0+Hello_1']
step 5, data: [b'TensorFlow_1+Hello_2+TensorFlow_2']


##  Speed up Dataset processing



**ds.interleave(map_func, cycle_length)**

map_func : map function to apply to each data instance

cycle_length : the number of data instances to process concurrently

We can use this feature to read and process multiple files concurrently.

In [0]:
graph = tf.Graph()
with graph.as_default():
  ds = tf.data.Dataset.from_tensor_slices(text_filenames)
  # consume the first two files in concurrently, and then the third file 
  ds = ds.interleave(lambda filename: tf.data.TextLineDataset(filename),
                     cycle_length=2)

  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  iterator = iterator.get_next()

iterate_and_print(iterator, graph)

step 0, data: b'Hello_0'
step 1, data: b'Hello_1'
step 2, data: b'TensorFlow_0'
step 3, data: b'TensorFlow_1'
step 4, data: b'Hello_2'
step 5, data: b'TensorFlow_2'


**ds.prefetch(buffer_size)** 

prefetch elements from a dataset. buffer size represents the maximum buffer size

In [0]:
graph = tf.Graph()
with graph.as_default():
  ds = tf.data.Dataset.from_tensor_slices(text_filenames)
  ds = ds.interleave(lambda filename: tf.data.TextLineDataset(filename),
                     cycle_length=3)
  ds = ds.prefetch(3)

  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  iterator = iterator.get_next()

iterate_and_print(iterator, graph)

step 0, data: b'Hello_0'
step 1, data: b'Hello_1'
step 2, data: b'Hello_2'
step 3, data: b'TensorFlow_0'
step 4, data: b'TensorFlow_1'
step 5, data: b'TensorFlow_2'


## Quiz 4
Create a dataset following the instructions.

1. Create a textline dataset using files named `ex_filenames`. 
2. Shuffle the dataset with buffer size 15.
3. Repeat the dataset for 2 epochs.
4. Convert each data instance using the `cast` function defined below.
5. Make the data instances as a batch (batch size = 3).



In [0]:
import random

def create_text_file(index):
  with open('ex_file_%d'%index, 'w') as f:
    for i in range(3):
      f.write('%d.%d\n' % (index, i))
    
ex_filenames = []
for i in range(5):
  create_text_file(i)
  ex_filenames.append('ex_file_%d'% i)

def cast(data):
  data = tf.strings.to_number(data, out_type=tf.float32)
  return data


graph = tf.Graph()
with graph.as_default():
  ############# Write here. ################
  ds = tf.data.TextLineDataset(ex_filenames)
  ds = ds.shuffle(10)
  ds = ds.repeat(2)
  ds = ds.map(cast)
  ds = ds.batch(3)
  ##########################################

  iterator = tf.compat.v1.data.make_one_shot_iterator(ds)
  iterator = iterator.get_next()

iterate_and_print(iterator, graph, count=10)

step 0, data: [0.2 1.  2.2]
step 1, data: [2.1 3.1 0. ]
step 2, data: [4.  2.  1.2]
step 3, data: [1.1 4.1 4.2]
step 4, data: [3.2 0.1 3. ]
step 5, data: [3.  2.1 2.2]
step 6, data: [2.  0.1 4.1]
step 7, data: [1.2 4.  1. ]
step 8, data: [1.1 3.2 0. ]
step 9, data: [3.1 0.2 4.2]


# 3. Logistic Regression

Now, we can build a logistic regression example on TensorFlow by following the steps below.

**1. Read MNIST data using the dataset API**

**2. Create weights and biases**

**3. Build a logistic regression model**

**4. Define a loss function**

**5. Define a training op**

**6. Train and calculate accuracy**

## Read MNIST data using the dataset API

In [0]:
from __future__ import division
from __future__ import print_function

import argparse
import gzip
import os
import sys
import urllib

try:
    from urllib.error import URLError
    from urllib.request import urlretrieve
except ImportError:
    from urllib2 import URLError
    from urllib import urlretrieve

RESOURCES = [
    'train-images-idx3-ubyte.gz',
    'train-labels-idx1-ubyte.gz',
    't10k-images-idx3-ubyte.gz',
    't10k-labels-idx1-ubyte.gz',
]


def report_download_progress(chunk_number, chunk_size, file_size):
    if file_size != -1:
        percent = min(1, (chunk_number * chunk_size) / file_size)
        bar = '#' * int(64 * percent)
        sys.stdout.write('\r0% |{:<64}| {}%'.format(bar, int(percent * 100)))


def download(destination_path, url, quiet):
    if os.path.exists(destination_path):
        if not quiet:
            print('{} already exists, skipping ...'.format(destination_path))
    else:
        print('Downloading {} ...'.format(url))
        try:
            hook = None if quiet else report_download_progress
            urlretrieve(url, destination_path, reporthook=hook)
        except URLError:
            raise RuntimeError('Error downloading resource!')
        finally:
            if not quiet:
                # Just a newline.
                print()


def unzip(zipped_path, quiet):
    unzipped_path = os.path.splitext(zipped_path)[0]
    if os.path.exists(unzipped_path):
        if not quiet:
            print('{} already exists, skipping ... '.format(unzipped_path))
        return
    with gzip.open(zipped_path, 'rb') as zipped_file:
        with open(unzipped_path, 'wb') as unzipped_file:
            unzipped_file.write(zipped_file.read())
            if not quiet:
                print('Unzipped {}!'.format(zipped_path))


mnist_dir = 'data/mnist'
if not os.path.exists(mnist_dir):
    os.makedirs(mnist_dir)


for resource in RESOURCES:
    path = os.path.join(mnist_dir, resource)
    url = 'http://yann.lecun.com/exdb/mnist/{}'.format(resource)
    download(path, url, False)
    unzip(path, False)

0% |################################################################| 100%
Unzipped data/mnist/train-images-idx3-ubyte.gz!
0% |################################################################| 100%
Unzipped data/mnist/train-labels-idx1-ubyte.gz!
0% |################################################################| 100%
Unzipped data/mnist/t10k-images-idx3-ubyte.gz!
0% |################################################################| 100%
Unzipped data/mnist/t10k-labels-idx1-ubyte.gz!


In [0]:
import struct
import numpy as np
import tensorflow as tf


# Parse each MNIST data instance as images and labels
def parse_data(path, dataset, flatten):
    if dataset != 'train' and dataset != 't10k':
        raise NameError('dataset must be train or t10k')

    label_file = os.path.join(path, dataset + '-labels-idx1-ubyte')
    with open(label_file, 'rb') as file:
        _, num = struct.unpack(">II", file.read(8))
        labels = np.fromfile(file, dtype=np.int8) #int8
        new_labels = np.zeros((num, 10))
        new_labels[np.arange(num), labels] = 1
    
    img_file = os.path.join(path, dataset + '-images-idx3-ubyte')
    with open(img_file, 'rb') as file:
        _, num, rows, cols = struct.unpack(">IIII", file.read(16))
        imgs = np.fromfile(file, dtype=np.uint8).reshape(num, rows, cols) #uint8
        imgs = imgs.astype(np.float32) / 255.0
        if flatten:
            imgs = imgs.reshape([num, -1])

    return imgs, new_labels
  
# Read in the mnist dataset, given that the data is stored in path
# Return two tuples of numpy arrays
# ((train_imgs, train_labels), (test_imgs, test_labels))
def read_mnist(path, flatten=True):
    train = parse_data(path, 'train', flatten)
    test = parse_data(path, 't10k', flatten)
    return train, test

mnist_dir = "data/mnist"
train, test = read_mnist(mnist_dir, flatten=True)

print(train[0].shape) # image
print(train[1].shape) # label
print(test[0].shape) # image
print(test[1].shape) # label

(60000, 784)
(60000, 10)
(10000, 784)
(10000, 10)


### Build an input pipeline using the dataset API

Create datasets from numpy arrays that contain MNIST data.
Then, batch them using batch size of 128.

In [0]:
train, test = read_mnist(mnist_dir, flatten=True)
batch_size = 128

graph = tf.Graph()
with graph.as_default():
  train_data = tf.data.Dataset.from_tensor_slices(train)
  train_data = train_data.shuffle(10000)
  train_data = train_data.batch(batch_size)

  test_data = tf.data.Dataset.from_tensor_slices(test)
  test_data = test_data.batch(batch_size)



  # create an empty iterator with only type and shape information
  iterator = tf.data.Iterator.from_structure(tf.compat.v1.data.get_output_types(train_data),
                                             tf.compat.v1.data.get_output_shapes(train_data))
  image, label = iterator.get_next()

  # create an operation for initializing the iterator with the train or test dataset
  train_init = iterator.make_initializer(train_data)
  test_init = iterator.make_initializer(test_data)

## Build a logistic regression model

`w` is initialized to random normal distribution variables with mean 0 and standard deviation 0.01.
`b` is initialized to 0's.
The shape of `w` depends on the dimensions of `image` and `label` so that `label = tf.matmul(image, w)`.
The shape of `b` depends on `label`.
The cross entropy of softmax of logits is our loss function.

In [0]:
with graph.as_default():
  w = tf.get_variable(name='weights_dataset', shape=(784, 10), initializer=tf.random_normal_initializer(0, 0.01))
  b = tf.get_variable(name='bias_dataset', shape=(1, 10), initializer=tf.zeros_initializer())
  logits = tf.matmul(image, w) + b
  loss = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits, labels=label)
  loss = tf.reduce_mean(loss) # average over all the examples in the batch

## Define a training op

We'll use an Adam optimizer with a learning rate of 0.001 to minimize loss.

In [0]:
with graph.as_default():
  optimizer = tf.train.AdamOptimizer(0.001)
  train_op = optimizer.minimize(loss)
  preds = tf.nn.softmax(logits)
  num_corrects = tf.equal(tf.argmax(preds, 1), tf.argmax(label, 1))
  num_corrects = tf.reduce_sum(tf.cast(num_corrects, tf.float32))

## Train and calculate accuracy

Finally, we train the model and use the test set to calculate the accuracy of our model.

In [0]:
with tf.Session(graph=graph) as sess:  
    sess.run(tf.global_variables_initializer())

    # train the model for 10 epochs
    for i in range(10):
        sess.run(train_init) # initialize the iterator using training set
        total_loss = 0
        n_batches = 0
        try:
            while True:
                _, l = sess.run([train_op, loss])
                total_loss += l
                n_batches += 1
        except tf.errors.OutOfRangeError:
            pass
        print('Epoch {0}: {1}'.format(i, total_loss/n_batches))   

        # test the model
        sess.run(test_init) # initialize the iterator using test set
        total_num_corrects = 0
        try:
            while True: 
                total_num_corrects += sess.run(num_corrects)
        except tf.errors.OutOfRangeError:
            pass
        print('Accuracy {0}'.format(total_num_corrects/10000))

Epoch 0: 0.6618076512045952
Accuracy 0.9016
Epoch 1: 0.35990982335894856
Accuracy 0.9116
Epoch 2: 0.31811390305632975
Accuracy 0.9175
Epoch 3: 0.29899842659039283
Accuracy 0.921
Epoch 4: 0.2871422721887194
Accuracy 0.9224
Epoch 5: 0.2789779175509776
Accuracy 0.9233
Epoch 6: 0.2731518240879848
Accuracy 0.9223
Epoch 7: 0.26868408991456794
Accuracy 0.9241
Epoch 8: 0.2651266718247552
Accuracy 0.9254
Epoch 9: 0.26204027306995414
Accuracy 0.9263
