In [1]:
import numpy as np

In [13]:
matrix = np.matrix([[2,2],[1,1]])

In [14]:
matrix

matrix([[2, 2],
        [1, 1]])

In [15]:
U, s, V = np.linalg.svd(matrix, full_matrices = True)


In [16]:
U

matrix([[-0.89442719, -0.4472136 ],
        [-0.4472136 ,  0.89442719]])

In [17]:
s

array([3.16227766e+00, 1.10062118e-17])

In [18]:
V

matrix([[-0.70710678, -0.70710678],
        [ 0.70710678, -0.70710678]])

In [22]:
S = np.zeros(matrix.shape)
for i in range(len(s)):
    S[i][i] = s[i]
print(S)

[[3.16227766e+00 0.00000000e+00]
 [0.00000000e+00 1.10062118e-17]]


In [26]:
np.dot(U, np.dot(S, V))

matrix([[2., 2.],
        [1., 1.]])