In [31]:
import numpy as np
eig = np.linalg.eig

# 2 by 2

In [32]:
matrix = np.matrix([[4,-2],[1,1]])
eigen = eig(matrix)

In [23]:
eigen_value = eigen[0]
print(eigen_value)

[3. 2.]


In [24]:
eigen_vector = eigen[1]
print(eigen_vector)

[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [25]:
print(eigen_vector[:,0] / eigen_vector[0,0])

[[1. ]
 [0.5]]


In [26]:
print(eigen_vector[:,1] / eigen_vector[0,1])

[[1.]
 [1.]]


# diagonal (eigen) decomposition


In [27]:
inv = np.linalg.inv

In [29]:
inv(eigen_vector) * matrix * eigen_vector # eigen value # numerical result

matrix([[3.00000000e+00, 2.54181891e-16],
        [4.36247471e-17, 2.00000000e+00]])

# 3 by 3

In [14]:
matrix = np.matrix([[2,-3,1],[1,-2,1],[1,-3,2]])
eigen = eig(matrix)

In [15]:
eigen_value = eigen[0]
print(eigen_value)
# [0,1,1]

[1.33226763e-15+0.00000000e+00j 1.00000000e+00+8.74190484e-16j
 1.00000000e+00-8.74190484e-16j]


In [16]:
eigen_vector = eigen[1]
print(eigen_vector)

[[-0.57735027+0.j          0.81103583+0.j          0.81103583-0.j        ]
 [-0.57735027+0.j          0.36250517-0.11591802j  0.36250517+0.11591802j]
 [-0.57735027+0.j          0.27647967-0.34775407j  0.27647967+0.34775407j]]


In [17]:
print(eigen_vector[:,0] / eigen_vector[0,0])

[[1.-0.j]
 [1.-0.j]
 [1.-0.j]]


In [18]:
print(eigen_vector[:,1] / eigen_vector[0,1])

[[1.        +0.j       ]
 [0.44696566-0.1429259j]
 [0.34089699-0.4287777j]]


In [19]:
print(eigen_vector[:,2] / eigen_vector[0,2])

[[1.        +0.j       ]
 [0.44696566+0.1429259j]
 [0.34089699+0.4287777j]]
