In [1]:
import pandas as pd

In [2]:
yes24 = pd.read_csv('./text-analytics/yes24-book-review-prep.csv', names=['name','id','text'])

In [3]:
yes24.head()

name            id  \
0             초한지 6  9.788937e+12   
1            폭풍의 언덕  9.791156e+12   
2         걸, 마돈나 세트  9.788993e+12   
3  커피점 탈레랑의 사건 수첩 2  9.791185e+12   
4           무의미의 축제  9.788937e+12   

                                                text  
0  단 한번 승리 천하 고조 유방 단 번의 패배 모든 것 초패 항우 이 책 유방 한우 ...  
1  인간 애증 격정 치명 복수 화제 드라마 비밀 의 모티프 폭풍 언덕 서른 해 생 살 ...  
2  걸 직장 여성 심리 리얼 유쾌하 소설 얼굴 잔 주름 이제 화장 발 이 제 나이 도 ...  
3  잔 커피 년 추억 터키 속담 교토 거리 뒤편 자리 커피점 탈레랑 미호 시 여동생 미...  
4  농담 거짓말 의미 무의미 일상 축제 경계 삶 인간 본질 더욱 원숙 해진 시선 수 존...

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [10]:
count_vectorizer = CountVectorizer()
count_vector = count_vectorizer.fit_transform(yes24.text)

tfidf_transformer = TfidfTransformer()
tfidf_featrues = tfidf_transformer.fit_transform(count_vector)

In [9]:
yes24.text[0]

'단 한번 승리 천하 고조 유방 단 번의 패배 모든 것 초패 항우 이 책 유방 한우 삶 초점 영웅 삶 파란만장 인생 풍운아 일대기 그린 책 유방 항우 무렵 전국시대 말기 진시황제 세 황제 호해 통일 진나라 시대 통일 진나라 멸망 항우 패 과정 이 승복 못 유방 반발 항우 끝내 천하 재 과정 생생 기원전 년 장량 시황제 암살 기도 장면 항우 기원전 년 초 년 이야기 초한지 천하 패권 겨룬 두 영웅 그 중심 호걸 야망 음모 충성 변절 거듭 초 쟁패 주인공 과정 우리 시대 대표 작가 이문열 그 접전 통해 동양 리더십 원형 그 진수 초한지 년 월말 총 권 발간 예정'

In [11]:
tfidf_featrues[0]

<1x46287 sparse matrix of type '<class 'numpy.float64'>'
	with 65 stored elements in Compressed Sparse Row format>

In [12]:
tfidf_featrues[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [13]:
query = ['개념 원리']
q = count_vectorizer.transform(query)
print(q)

  (0, 903)	1
  (0, 29203)	1


In [14]:
import numpy as np

print(q.toarray())
print(tfidf_featrues[0].toarray())

[[0 0 0 ... 0 0 0]]
[[0. 0. 0. ... 0. 0. 0.]]


In [15]:
print(np.inner(q.toarray(), tfidf_featrues[0].toarray()))
print(np.inner(q.toarray(), tfidf_featrues[12].toarray()))

[[0.]]
[[0.04064417]]


In [16]:
from scipy.spatial import distance
print(distance.cosine(q.toarray(), tfidf_featrues[0].toarray()))
print(distance.cosine(q.toarray(), tfidf_featrues[12].toarray()))

1.0
0.9712602286618821


In [28]:
tfidf_featrues[12].toarray().shape

(1, 46287)