# 선형대수학

In [3]:
import numpy as np
from scipy import linalg as la

In [4]:
A = np.array([[2,1,1], [2,1,-1],[1,3,1]])

In [5]:
A.shape

(3, 3)

In [6]:
P, L, U = la.lu(A)

In [7]:
P

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [8]:
L

array([[1. , 0. , 0. ],
       [0.5, 1. , 0. ],
       [1. , 0. , 1. ]])

In [9]:
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  0.5],
       [ 0. ,  0. , -2. ]])

In [10]:
def plusol (A, b):
    m,n = A.shape
    P, L, U = la.lu(A)
    y = np.zeros((m,1))
    c = np.dot (P,b)
    
    for j in range(m):
        y[j] = c[j] - np.dot(L[j, :j], y[:j])
        
    x = np.zeros((n,1))
    
    for j in range(n-1, -1, -1):
        x[j] = (y[j] - np.dot(U[j, j+1:], x[j+1:])) / U[j, j]
    
    return x

In [11]:
b = np.array([[1],[1],[1]])
np.dot(A, plusol(A, b))

array([[1.],
       [1.],
       [1.]])

In [12]:
plusol(A, b)

array([[ 0.4],
       [ 0.2],
       [-0. ]])

In [13]:
np.dot(A, plusol(A, b))

array([[1.],
       [1.],
       [1.]])