In [5]:
import numpy as np

In [6]:
eig = np.linalg.eig

In [11]:
matrix = np.matrix([[4, -2], [1, 1]])

In [30]:
eigen = eig(matrix)
eigen

(array([3., 2.]), matrix([[0.89442719, 0.70710678],
         [0.4472136 , 0.70710678]]))

In [27]:
eigen_value = eigen[0]
print(eigen_value)

[3. 2.]


In [28]:
eigen_vector = eigen[1]
print(eigen_vector)

[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [29]:
print(eigen_vector[:,0] / eigen_vector[0, 0])

[[1. ]
 [0.5]]


In [31]:
inv = np.linalg.inv

In [33]:
inv(eigen_vector) * matrix * eigen_vector # inv(V)*A*(V)

matrix([[3., 0.],
        [0., 2.]])

In [34]:
A = np.array([[2,-3,1],[1,-2,1],[1,-3,2]])

In [41]:
eigen = eig(A)
eigen_value = eigen[0]
eigen_value

array([1.33226763e-15+0.00000000e+00j, 1.00000000e+00+8.74190484e-16j,
       1.00000000e+00-8.74190484e-16j])

In [43]:
eigen_vector = eigen[1]

In [45]:
eigen_vector

array([[-0.57735027+0.j        ,  0.81103583+0.j        ,
         0.81103583-0.j        ],
       [-0.57735027+0.j        ,  0.36250517-0.11591802j,
         0.36250517+0.11591802j],
       [-0.57735027+0.j        ,  0.27647967-0.34775407j,
         0.27647967+0.34775407j]])

In [53]:
A = np.array([[2,2],[1,1]])
u, s, v = np.linalg.svd(A)


In [54]:
u

array([[-0.89442719, -0.4472136 ],
       [-0.4472136 ,  0.89442719]])