In [14]:
# __name__ == "__main__"의 의미
# 현재 실행하고 있는 파일 True, main() 함수 역할
# import 한 경우에는 __name__에 파일 이름이 저장되어 False

### ch15의 p4 내용 변경함

In [15]:
import numpy
print(numpy.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [23]:
from numpy import arange
print(arange(10))
print(numpy.max(arange(10)))

[0 1 2 3 4 5 6 7 8 9]
9


In [24]:
from numpy import *
print(arange(10))

[0 1 2 3 4 5 6 7 8 9]
